# Generated by Django 2.1.3 on 2018-11-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='bible_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
