# Generated by Django 2.1.3 on 2018-11-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0003_remove_monster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=3)),
                ('attribute', models.CharField(max_length=50)),
            ],
        ),
    ]
