# Generated by Django 2.1.3 on 2018-11-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0004_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monsterapi.Name'),
        ),
    ]
