# Generated by Django 2.1.3 on 2018-11-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0005_monster_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melody',
            name='description',
        ),
        migrations.RemoveField(
            model_name='melody',
            name='rism_notes',
        ),
        migrations.AddField(
            model_name='melody',
            name='mei_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
