# Generated by Django 2.1.3 on 2018-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0007_auto_20181109_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, default='media/monster_pics/leo.png', null=True, upload_to='media/monster_pics/'),
        ),
    ]
