# Generated by Django 2.1.3 on 2018-11-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0008_monster_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='printer',
            new_name='printer_id',
        ),
    ]
