# Generated by Django 2.1.3 on 2018-11-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0009_auto_20181115_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='melody',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='melody',
            name='clef',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='gwv',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='instrument',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='keysig',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='pae_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='timesig',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
