# Generated by Django 2.1.3 on 2018-11-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0010_auto_20181115_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['attribute', 'name']},
        ),
    ]
