# Generated by Django 2.1.3 on 2018-11-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0011_auto_20181117_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['gender', 'name', 'attribute']},
        ),
    ]
