# Generated by Django 2.1.3 on 2018-11-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0012_auto_20181117_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='melody',
            options={'verbose_name_plural': 'melodies'},
        ),
    ]
