# Generated by Django 2.1.3 on 2018-11-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0013_auto_20181117_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='monsterapi.Book'),
        ),
    ]
