# Generated by Django 2.1.3 on 2018-11-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0016_auto_20181120_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melody',
            name='gwv',
        ),
        migrations.RemoveField(
            model_name='melody',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='melody',
            name='mei_data',
        ),
        migrations.RemoveField(
            model_name='melody',
            name='title',
        ),
        migrations.AddField(
            model_name='melody',
            name='movement',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='rism_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='rism_opac_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='tu_da_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='melody',
            name='work_title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
