# Generated by Django 2.1.3 on 2018-11-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0017_auto_20181120_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melody',
            name='clef',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='melody',
            name='keysig',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='melody',
            name='movement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='melody',
            name='timesig',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='melody',
            name='work_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
