# Generated by Django 2.1.3 on 2018-11-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0018_auto_20181121_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='picture_id',
            new_name='picture_slug',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='image',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='motives',
        ),
    ]
