# Generated by Django 2.1.3 on 2018-11-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0019_auto_20181121_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ['name']},
        ),
    ]
