# Generated by Django 2.1.3 on 2018-11-23 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0021_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='melody3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='melody3', to='monsterapi.Melody'),
        ),
        migrations.AlterField(
            model_name='game',
            name='melody2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='melody2', to='monsterapi.Melody'),
        ),
    ]
