# Generated by Django 2.1.3 on 2018-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0023_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
