# Generated by Django 2.1.3 on 2018-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0024_book_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
