# Generated by Django 2.1.3 on 2018-11-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0025_auto_20181127_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['gender', 'forename', 'attribute']},
        ),
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='forename',
        ),
    ]
