# Generated by Django 2.1.3 on 2018-11-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0026_auto_20181129_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='melody',
            new_name='tested_melody',
        ),
    ]
