# Generated by Django 2.1.3 on 2018-11-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0027_auto_20181129_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
